// <auto-generated />
namespace Project_2___Online_Movie_Viewer.DataContexts.MovieProfileMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddProfileId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProfileId));
        
        string IMigrationMetadata.Id
        {
            get { return "201611070000284_AddProfileId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
